<?php

namespace ContainerUZtaJPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\IndexController' shared autowired service.
     *
     * @return \App\Controller\Admin\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/server/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/server/src/Controller/Admin/AdminController.php';
        include_once \dirname(__DIR__, 4).'/server/src/Controller/Admin/IndexController.php';

        $container->services['App\\Controller\\Admin\\IndexController'] = $instance = new \App\Controller\Admin\IndexController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\IndexController', $container));

        return $instance;
    }
}
