<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYWJ90QY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYWJ90QY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYWJ90QY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYWJ90QY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYWJ90QY\App_KernelDevDebugContainer([
    'container.build_hash' => 'YWJ90QY',
    'container.build_id' => '8264cad1',
    'container.build_time' => 1769765907,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYWJ90QY');
