<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUZtaJPn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUZtaJPn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUZtaJPn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUZtaJPn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUZtaJPn\App_KernelDevDebugContainer([
    'container.build_hash' => 'UZtaJPn',
    'container.build_id' => 'f3706cb5',
    'container.build_time' => 1769576904,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUZtaJPn');
