<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt_stylesheet' => [[], ['_controller' => 'web_profiler.controller.profiler::toolbarStylesheetAction'], [], [['text', '/_wdt/styles']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\Admin\\IndexController::index'], [], [['text', '/admin/']], [], [], []],
    'admin_settings' => [[], ['_controller' => 'App\\Controller\\Admin\\IndexController::settings'], [], [['text', '/admin/settings']], [], [], []],
    'admin_login' => [[], ['_controller' => 'App\\Controller\\Admin\\LoginController::login'], [], [['text', '/admin/login']], [], [], []],
    'admin_logout' => [[], ['_controller' => 'App\\Controller\\Admin\\LoginController::logout'], [], [['text', '/admin/logout']], [], [], []],
    'index' => [['reactRouting'], ['reactRouting' => null, '_controller' => 'App\\Controller\\HomeController::index'], ['reactRouting' => '(?!api|_profiler|_wdt|assets|favicon).*'], [['variable', '/', '(?!api|_profiler|_wdt|assets|favicon).*', 'reactRouting', true]], [], [], []],
    'App\Controller\Admin\IndexController::index' => [[], ['_controller' => 'App\\Controller\\Admin\\IndexController::index'], [], [['text', '/admin/']], [], [], []],
    'App\Controller\Admin\IndexController::settings' => [[], ['_controller' => 'App\\Controller\\Admin\\IndexController::settings'], [], [['text', '/admin/settings']], [], [], []],
    'App\Controller\Admin\LoginController::login' => [[], ['_controller' => 'App\\Controller\\Admin\\LoginController::login'], [], [['text', '/admin/login']], [], [], []],
    'App\Controller\Admin\LoginController::logout' => [[], ['_controller' => 'App\\Controller\\Admin\\LoginController::logout'], [], [['text', '/admin/logout']], [], [], []],
    'App\Controller\HomeController::index' => [['reactRouting'], ['reactRouting' => null, '_controller' => 'App\\Controller\\HomeController::index'], ['reactRouting' => '(?!api|_profiler|_wdt|assets|favicon).*'], [['variable', '/', '(?!api|_profiler|_wdt|assets|favicon).*', 'reactRouting', true]], [], [], []],
];
