<?php

namespace ContainerW5dRzoa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Modules\Users\Controller\Admin\UserController' shared autowired service.
     *
     * @return \App\Modules\Users\Controller\Admin\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/server/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/server/src/Controller/Admin/AdminController.php';
        include_once \dirname(__DIR__, 4).'/server/src/Modules/Users/Controller/Admin/UserController.php';

        $container->services['App\\Modules\\Users\\Controller\\Admin\\UserController'] = $instance = new \App\Modules\Users\Controller\Admin\UserController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Modules\\Users\\Controller\\Admin\\UserController', $container));

        return $instance;
    }
}
